// Code generated by MockGen. DO NOT EDIT.
// Source: d7y.io/dragonfly/v2/cdn/supervisor/progress (interfaces: Manager)

// Package mock is a generated GoMock package.
package progress

import (
	context "context"
	reflect "reflect"

	task "d7y.io/dragonfly/v2/cdn/supervisor/task"
	gomock "github.com/golang/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockManager) Clear(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear", arg0)
}

// Clear indicates an expected call of Clear.
func (mr *MockManagerMockRecorder) Clear(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockManager)(nil).Clear), arg0)
}

// GetPieces mocks base method.
func (m *MockManager) GetPieces(arg0 string) ([]*task.PieceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPieces", arg0)
	ret0, _ := ret[0].([]*task.PieceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPieces indicates an expected call of GetPieces.
func (mr *MockManagerMockRecorder) GetPieces(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPieces", reflect.TypeOf((*MockManager)(nil).GetPieces), arg0)
}

// InitSeedProgress mocks base method.
func (m *MockManager) InitSeedProgress(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitSeedProgress", arg0, arg1)
}

// InitSeedProgress indicates an expected call of InitSeedProgress.
func (mr *MockManagerMockRecorder) InitSeedProgress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitSeedProgress", reflect.TypeOf((*MockManager)(nil).InitSeedProgress), arg0, arg1)
}

// PublishPiece mocks base method.
func (m *MockManager) PublishPiece(arg0 context.Context, arg1 string, arg2 *task.PieceInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPiece", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPiece indicates an expected call of PublishPiece.
func (mr *MockManagerMockRecorder) PublishPiece(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPiece", reflect.TypeOf((*MockManager)(nil).PublishPiece), arg0, arg1, arg2)
}

// PublishTask mocks base method.
func (m *MockManager) PublishTask(arg0 context.Context, arg1 string, arg2 *task.SeedTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTask indicates an expected call of PublishTask.
func (mr *MockManagerMockRecorder) PublishTask(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTask", reflect.TypeOf((*MockManager)(nil).PublishTask), arg0, arg1, arg2)
}

// WatchSeedProgress mocks base method.
func (m *MockManager) WatchSeedProgress(arg0 context.Context, arg1 string) (<-chan *task.PieceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchSeedProgress", arg0, arg1)
	ret0, _ := ret[0].(<-chan *task.PieceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchSeedProgress indicates an expected call of WatchSeedProgress.
func (mr *MockManagerMockRecorder) WatchSeedProgress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchSeedProgress", reflect.TypeOf((*MockManager)(nil).WatchSeedProgress), arg0, arg1)
}
