// Code generated by MockGen. DO NOT EDIT.
// Source: d7y.io/dragonfly/v2/cdn/supervisor (interfaces: CDNManager)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	types "d7y.io/dragonfly/v2/cdn/types"
	gomock "github.com/golang/mock/gomock"
)

// MockCDNManager is a mock of CDNManager interface.
type MockCDNManager struct {
	ctrl     *gomock.Controller
	recorder *MockCDNManagerMockRecorder
}

// MockCDNManagerMockRecorder is the mock recorder for MockCDNManager.
type MockCDNManagerMockRecorder struct {
	mock *MockCDNManager
}

// NewMockCDNManager creates a new mock instance.
func NewMockCDNManager(ctrl *gomock.Controller) *MockCDNManager {
	mock := &MockCDNManager{ctrl: ctrl}
	mock.recorder = &MockCDNManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCDNManager) EXPECT() *MockCDNManagerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCDNManager) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCDNManagerMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCDNManager)(nil).Delete), arg0)
}

// TriggerCDN mocks base method.
func (m *MockCDNManager) TriggerCDN(arg0 context.Context, arg1 *types.SeedTask) (*types.SeedTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerCDN", arg0, arg1)
	ret0, _ := ret[0].(*types.SeedTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerCDN indicates an expected call of TriggerCDN.
func (mr *MockCDNManagerMockRecorder) TriggerCDN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerCDN", reflect.TypeOf((*MockCDNManager)(nil).TriggerCDN), arg0, arg1)
}

// TryFreeSpace mocks base method.
func (m *MockCDNManager) TryFreeSpace(arg0 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryFreeSpace", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryFreeSpace indicates an expected call of TryFreeSpace.
func (mr *MockCDNManagerMockRecorder) TryFreeSpace(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryFreeSpace", reflect.TypeOf((*MockCDNManager)(nil).TryFreeSpace), arg0)
}
